apt40_file_iocs:
  columns:
  - column_index: 0
    column_type: STRING
    key_column: true
    mapped_column_path: null
    original_column: hash
  description: File IOCs associated with APT40
  row_time_to_live: null
  rule_associations_count: null
  rules: null
